name: javascript-CI

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  ci_to_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run test-once
  coverage: 
    runs-on: ubuntu-latest
    steps:
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.2.1
        id: coverage
        with:
            output: report-markdown, comment
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
            message: ${{ steps.coverage.outputs.report }}